version: '3'

services:
  web:
    build: web

    environment:
      CRONSUN_WEB_BIND_ADDRESS: ":8080"
      CRONSUN_DB_HOST: "mongo:27017"
      CRONSUN_ETCD_ENDPOINT: "http://etcd:2379"

    ports:
      - "8080:8080"

  node:
    build: node

    environment:
      HOSTNAME: node_01.mydomain.com
      CRONSUN_DB_HOST: "mongo:27017"
      CRONSUN_ETCD_ENDPOINT: "http://etcd:2379"

    depends_on:
      - etcd

  etcd:
    image: "quay.io/coreos/etcd"

    environment:
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_NAME: etcd
      ETCD_DATA_DIR: /data

    ports:
      - "2379:2379"
      - "2380:2380"

    restart: always

    volumes:
      - "./data/etcd:/data"

  mongo:
    image: mongo:3.3

    restart: always

    ports:
      - "27017:27017"

    volumes:
      - ./data/mongo:/data/db

  mongo_express:
    image: mongo-express

    restart: always

    ports:
      - "8081:8081"

    environment:
      ME_CONFIG_MONGODB_SERVER: mongo

    depends_on:
      - mongo
